### ISSUE TITLE
'requests.received_headers' with some devices didn't exist.

### ISSUE THREAD

**Issue by rouxpi** [opacam/Cohen3#20]
Using:
`cohen3 --plugin=backend:FSStore,content:/media/RouxpiTech`

And streaming some content will fail with:
`File "/home/RouxpiTech/.local/lib/python3.6/site-packages/coherence/upnp/devices/media_server.py", line 388, in process_child del request.received_headers[b'content-length'] builtins.AttributeError: 'Request' object has no attribute 'received_headers'`

I have tested with other devices, and this error only happens on some devices.

It fails with Samsung TVs
And it was succesfull in iOS.

**Comment by RouxpiTech** [comment]
Better solution to problem :100:
